version: '3.5'

services:

  mongo:
    image: mongo:4
    restart: always
    container_name: mongo_db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo_default
    

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks:
      - mongo_default

networks:
  mongo_default:
    name: mongo_default